language: node_js
node_js:
- node
- '8'
script:
- npm run compileOnce
- npm run testInternal
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: "RlkPyeCIoq87rJ6oXcS0kl8KYdFOd4OJEA+7YYZ6rAlXt4MqpMHbfDcJSrxXKFCVxQsQqe6LcDkBz0ao4hYD9p+HKaxovXEXs71I3dGc6EVICkfEbC7CQwGHP5R6vZFYjdWLn5kddyX72f+OgQBTj8Sk66RZNAf+31pibfLckmG4IKRGAOu6fkr2pkDmRbyhje+QqwwL+x5jNya5fSqZCaMHKyW9sY08CxB82chrxVMc1FzHn/NH4LWHQwTps9gNiu2Rb3bxyQkzg42wVysGj/+T/rAEB1afheIQvd9FHdnFSfI/HaUiBvQ0KGp7bSmhXM7OKPUEKkJZghXuctfxo+jSuSeeqt2A1yARW6IBW5VR74aNUg8A3rADGzdo+UdyOx9KQw7TtOez1ma3iq7pyzlJONW+yEaBw0gtWIHctFtHeeZjBySjhakbeDa1i3gREHmOJlmAXuFwoMc87M01BClonzHcvuJtriQuH7sRVXPlK20OFx83AB0y5tqje015HchcUIu01QPMwhofdC0Si7yf0Co/eonmI/u9pcQA6HpPSa2VL6bq596wqJFOR8ZGQgXW48Ukto+uQ2qapLSS63n3gVzzEWtlzPRJbfS7C7hKklu7qvCCfTbkf9SfoWKiRVQmq6SbnYGuR/0cVn9WxPkeewSV7yyw9XDhYCIW8oU="
    app: blooming-fjord-15263
